version: 2
jobs:
  build:
    working-directory: ~/circleci-test
    docker: 
      - image: circleci/python:2-stretch
    steps:
      - run: sudo apt install jq
      - run: curl -s https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM} | jq -r '.workflows.workflow_name'


workflows:
  version: 2
  build_flow:
    jobs:
      - build
