version: 2
jobs:
  build:
    docker: 
      - image: circleci/python:2-stretch
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t wurbanskinx/ci-test:test-1 .
          docker push wurbanskinx/ci-test:test-1

  run:
    docker:
      - image: wurbanskinx/ci-test:test-1
    steps:
      - run: cat /test_file



workflows:
  version: 2
  build_flow:
    jobs:
      - build
      - run:
          requires:
            - build
