version: 2
jobs:
  build:
    working-directory: ~/circleci-test
    docker: 
      - image: circleci/python:2-stretch
    steps:
      - run: env
      - run: curl https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM}


workflows:
  version: 2
  build_flow:
    jobs:
      - build
