version: 2
jobs:
  build:
    docker: 
      - image: circleci/python:2-stretch
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build -t wurbanskinx/ci-test:test-${CIRCLE_SHA1} .
          docker push wurbanskinx/ci-test:test-${CIRCLE_SHA1}

  run:
    docker:
      - image: wurbanskinx/ci-test:test-${CIRCLE_SHA1}
    steps:
      - run: cat /test_file



workflows:
  version: 2
  build_flow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - test
            tags:
              only: /^v.*/
      - hold:
          type: approval
          requires:
            - build
      - run:
          requires:
            - build
