version: 2
jobs:
  build:
    working-directory: ~/circleci-test
    docker: 
      - image: circleci/python:2-stretch
    steps:
      - run: env

workflows:
  version: 2
  build_flow:
    jobs:
      - build
